apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: maksonik/sfm:0.1.1
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          command:
            - gunicorn
            - sfm.core.main:app
            - --workers=4
            - --worker-class=uvicorn.workers.UvicornWorker
            - --bind=0.0.0.0:8000
          livenessProbe:
            httpGet:
              path: /v1/healthcheck
              port: 8000
            initialDelaySeconds: 15     # Дать приложению стартовать
            periodSeconds: 10           # Проверять не слишком часто
            timeoutSeconds: 5           # Ждать до 5 секунд на ответ
            failureThreshold: 5
          env:
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: logs
              mountPath: /var/log/myapp
      volumes:
        - name: logs
          emptyDir: {}