apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://stage-prometheus:9090
        isDefault: true
        editable: true
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://stage-loki:3100
        isDefault: false
