apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  config.yaml: |
    server:
      http_listen_port: 9080
    positions:
      filename: /tmp/positions.yaml
    clients:
      - url: http://stage-loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: kubernetes-pods
        static_configs:
          - targets:
              - localhost
            labels:
              job: varlogs
              __path__: /var/log/pods/*/*/*.log
