namePrefix: prod-
resources:
  - ../../base
patches:
  - path: patches/deployment.yaml
    target:
      kind: Deployment
      name: myapp

secretGenerator:
  - envs:
      - secret.env
    name: secret